TARGET=driver_pengolahan

all:
	gcc pengolahan.c ../liststatik/liststatik.c ../resep/tree.c ../peta/peta.c ../point/point.c ../makanan/makanan.c ../word-machine/wordmachine.c ../inventory/inventory.c ../time/time.c